### ISSUE TITLE
Create setup.cfg file for nosetests

### ISSUE THREAD

**Issue by sdalbery** [DEVOPSRECOMMENDATIONS/recommendations#11]
**As a** developer
**I need** a setup.cfg file
**So that** I only have to type "nosetests" to run the test suite

**Assumptions:**
* the setup.cfg file will contain all our "nosetests" options

**Acceptance Criteria:**
```
When a developer types "nosetests"
Then the test suite will run
```

**Comment by sa6219** [comment]
This will be update as we learn more about testing process.
