### ISSUE TITLE
Update product recommendations

### ISSUE THREAD

**Issue by nsh240** [DEVOPSRECOMMENDATIONS/recommendations#13]
**As a** marketing manager
**I need** to modify an existing recommendation
**So that** I can update a recommendation

**Assumptions:**
* Written in Python
* There are two ways a recommendation can be updated: the link between the products and the type of recommendation

**Acceptance Criteria:**
```
When a marketing manager modifies the product link or type of recommendation
Then the recommendation will be updated in the database
```

**Comment by nsh240** [comment]
I may have made this too specific.  But I think we could create MANY stories for update- i.e. Update a recommendation based on a new user purchase, update recommendation based on a new product, etc.- just put in this one story for now but can expand it out

**Comment by sa6219** [comment]
This will be divided to three issues later with up-sell, accessory, and cross-sell
