### ISSUE TITLE
Create a skeleton app

### ISSUE THREAD

**Issue by sa6219** [DEVOPSRECOMMENDATIONS/recommendations#5]
**As a** developer
**I need** starter project with skeleton code 
**So that** I can add new features

**Assumptions:**
* We will need a skeleton service
* We will need a skeleton test case

**Acceptance Criteria:**
```
Given I have a skeleton project
When I clone the project to my local machine
Then I will have a starting point that runs and passes test cases
```

**Comment by sdalbery** [comment]
NOTE: Come back to this after watching video
