### ISSUE TITLE
Create product recommendations

### ISSUE THREAD

**Issue by sa6219** [DEVOPSRECOMMENDATIONS/recommendations#6]
**As a** a Marketing Manager
**I need** to create a recommendation
**So that** I can offer users recommendations

**Assumptions:**
* We are using Python
* There are products in the database
* There is a database to store the recommendations

**Acceptance Criteria:**
```
When I create a new recommendation
Then I can link two products together
And I can define the link as an upsell, cross-sell, or accessory
```

**Comment by sa6219** [comment]
We can look at the acceptance criteria from two different perspectives here: 1- Since the Issue is being created from the Marketing Manger perspective, when/how to add the recommendation can be the criteria 2- Even though the issue is being created from Marketing Manger perspective, her/his criteria (final goal) can align with customer: i.e. "when a new product is added, then s/he (customers) will see its recommendations when they look it up or buy it. We can discuss it during the meeting.

**Comment by nsh240** [comment]
If we have a user interface, we can add to this story: the user should see the recommendation for product "B" if the user enters product "A"
